### ISSUE TITLE
Error installing from source on Ruby 3.2

### ISSUE THREAD

**Issue by ankane** [oxidize-rb/oxi-test#4]
Hey @ianks, when installing the gem from source on Ruby 3.2.0-preview2:

```sh
bundle exec rake build
gem install --verbose --local pkg/oxi-test-0.1.0.gem
```

it fails with:

```text
Make sure you set "crate-type" in Cargo.toml to "cdylib"
```

From what I can tell, it's due to `Cargo.toml` having a different name than the gem name.

**Comment by ianks** [comment]
Hey @ankane, tbh I forgot to configure a source gem properly. Just fixed in #5

**Comment by ankane** [comment]
Great, thanks!

**Comment by ianks** [comment]
Sure thing! If you have other questions, come hang out in the [Ruby on Rust Slack](https://join.slack.com/t/oxidize-rb/shared_invite/zt-16zv5tqte-Vi7WfzxCesdo2TqF_RYBCw). Number of us hang out there!
